### ISSUE TITLE
Error unable to open database file

### ISSUE THREAD

**Issue by StevenNexus** [fiLLLip/plex-watched-sync#1]
Tried to use the client script today to sync my Plex server and got the follow message when I ran the command manually from the command line. On Ubuntu 16.04.

`~/plex-watched-sync/client$ sudo python sync.py`
`Error unable to open database file:`

Props config:
```
BASE_URL = "http://plexsync.filllip.net:8080/api"  # Server url without trailing slash.
SERVER_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # Log into plex and find "machineIdentifier" for this server at https://plex.tv/pms/servers.xml
DB_PATH = "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/"  # Path to Plex DB
ADMIN_ACCOUNT_REAL_ID = xxxxxxx  # In local Plex DB admins account is 1 (most like your account). Log into plex and find your ID here https://plex.tv/users/account
```

I have registered on your http://plexsync.filllip.net:8080 site.

**Comment by fiLLLip** [comment]
Hi, sorry for the late reply but I did not receive a notification on this.

As for your error, it seems like the sync.py-script does not find the Plex database file, and I see your DB_PATH is not complete.
My DB_PATH looks like this:
`DB_PATH = "/home/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db"  # Path to Plex DB`

I updated the props sample to show this

**Comment by StevenNexus** [comment]
Thank you, I'll make the edits to my config file.
